replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/sodium-petal-465008-t0/stm-repository/stm-project
  tag: build-22
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  name: project-services
  type: ClusterIP
  port: 5001

containerPort: 5001

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: user.khangesh.store
      paths:
        - path: /projects(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: user-service-tls
      hosts:
        - user.khangesh.store

# Environment variables
env:
  - name: DATABASE_URL
    value: postgresql://postgres:postgres@postgres-db:5432/projects_db
  - name: SECRET_KEY
    value: another-super-secret-key

# Optional: If you store env vars in a Kubernetes secret
envSecretName: project-service-secret

# Command and args to run app (e.g., Gunicorn, Flask, etc.)
command: ["gunicorn"]
args: ["-w", "4", "-b", "0.0.0.0:5001", "wsgi:app"]

# Postgres details for init container
postgres:
  host: postgres-db
  port: 5432
  user: postgres
  secretName: postgres-db-secret

# Health checks
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
