replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/sodium-petal-465008-t0/stm-repository/stm-user
  tag: build-38
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  name: user-services
  type: ClusterIP
  port: 5000

containerPort: 5000

ingress:
  enabled: true
  className: nginx
  name: user-services
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: user.khangesh.store
      paths:  
        - path: /users(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: user-service-tls
      hosts:
        - user.khangesh.store

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

env:
  - name: DATABASE_URL
    value: postgresql://postgres:postgres@postgres-db:5432/users_db
  - name: SECRET_KEY
    value: super-secret-key 

command: ["gunicorn"]
args: ["-w", "4", "-b", "0.0.0.0:5000", "wsgi:app"]

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

postgres:
  host: postgres-db
  port: 5432
  user: postgres
  secretName: postgres-db-secret

envSecretName: user-service-secret

